apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app-deployment
  labels:
    app: banking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-app
  template:
    metadata:
      labels:
        app: banking-app
    spec:
      containers:
      - name: banking-container
        image: abhishekpande285/bankapp-eta-app:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: banking-app-service
spec:
  type: NodePort
  selector:
    app: banking-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32000
